import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-amber-50 p-1"><nav>witam</nav>
        {children}
      </body>
    </html>
  );
}
